server:
  port: 8353
  servlet:
    jsp:
      init-parameters:
        development=true: # jsp 라이브 서버



spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: pjt
    password: 123


  #  # 파일 사이즈 관리
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB


# 시큐리티 기본 아이디 비밀번호
  security:
    user:
      name: pjt
      password: 123


## jpa 기본 셋팅
  jpa:
    show-sql: true # 콘솔에 sql 문 안나옴
    hibernate:
      ddl-auto: update

## 뷰단 기본 경로 설정
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # gmail Transfer SMTP
  # 메일 셋팅
  mail:
    host: smtp.gmail.com
    port: 587
    username: didtmdghks234@gmail.com
    password: ahjf eqvq laqi luue
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

# 마이바티스 매퍼 설정
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/**/*.xml
